### ISSUE TITLE
Datagen AutoPilot agent getting stuck

### ISSUE THREAD

**Issue by mathiaswold** [opendilab/InterFuser#30]
Hi!

Thank you for the open source project :)

We are trying to generate data for training using your data generation scripts. Note that we have upgraded to CARLA version 0.9.14 and thus had to change some code in our InterFuser fork, but no changes were done to the auto pilot agent. We are also using another car than the default lincoln mkz 2017 (they have similar dimensions).

While inspecting the data it generates, we see that the ego vehicle sometimes gets stuck when trying to do a turn. After a while it either despawns the incoming vehicle, or the scenario ends with a "Failed - Agent timed out"-error.

See videos below showcasing the problem. Would it for example be possible to change som variables in the code to increase the distance threshold between the ego vehicle and incoming cars during a turn?

https://user-images.githubusercontent.com/45951843/233123007-a9ec7b4b-bceb-4b59-a97d-41b127521401.mp4

https://user-images.githubusercontent.com/45951843/233123022-395f2f6e-9956-4d6c-b860-f6208b9c38f1.mp4

https://user-images.githubusercontent.com/45951843/233123033-a479612e-5d8c-4918-8fe5-ed64659a2e56.mp4

**Comment by deepcs233** [comment]
Hi!
This problem is very common in the process of collecting data. In our code, we do two things to walk around this problem:
1. Here([        if self.destory_hazard_actors:](https://github.com/opendilab/InterFuser/blob/e0682c350892a243cf40bf448622743f4b26d0f3/leaderboard/team_code/auto_pilot.py#L271)), we detect the actors that stay still for a long time and destroy them.
2. Although we have destoried some stationary actors, the collected dataset exists a lot of frames which are almost the same (the actors which stay still for 1500 game frames will be destoried). We provide some tools (tools/data/batch_rm_haze_data.py, tools/data/batch_recollect_blocked_data.py, tools/data/batch_stat_blocked_data.py) to delete these duplicated frames of the collected dataset.

But i don't konw whether CARLA 0.9.14 increases the probability of this problem. Hope the above can help you!

**Comment by mathiaswold** [comment]
Thank you, will look into this! :)
