### ISSUE TITLE
agent stoped by pedestrian standing still

### ISSUE THREAD

**Issue by JkhwungII** [opendilab/InterFuser#76]
Hi,  as the title said

we can  see that the pedestrian is clearly behind fence and standing still
![image](https://github.com/opendilab/InterFuser/assets/53292322/ab19a788-7bd8-46b8-a455-8eaa652130ac)

However, the agent predicts the pedestrian will move forward and stop the car
![image](https://github.com/opendilab/InterFuser/assets/53292322/0daef825-700d-44f9-89cc-3acd77f3954a)

I'd like to know is there a way to fix this problem

https://github.com/opendilab/InterFuser/assets/53292322/1137afae-9261-4579-9b7f-7f91f891ed35

**Comment by deepcs233** [comment]
Hi!

There are a lot of small problems like this when evaluate the agent in the Carla Leaderboard Benchmark. They are hard to be solved completely. Because the traffic environment is very complex, incuding different towns, randomness, and different scenarios. A good way to solve it is to evaluate your agent multiple times and get the average score.

**Comment by JkhwungII** [comment]
thanks
